"""add_comment_to_raw_materials_and_packaging

Revision ID: 2c6f7fffea5d
Revises: d7b56203f41c
Create Date: 2026-05-22 07:50:24.328017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6f7fffea5d'
down_revision: Union[str, Sequence[str], None] = 'd7b56203f41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('packaging_catalog', sa.Column('comment', sa.String(), nullable=False, server_default=''))
    op.add_column('raw_materials_catalog', sa.Column('comment', sa.String(), nullable=False, server_default=''))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_materials_catalog', 'comment')
    op.drop_column('packaging_catalog', 'comment')
    # ### end Alembic commands ###
