"""add_comment_to_customers

Revision ID: 634c0e911306
Revises: d749588bb9ad
Create Date: 2026-05-22 08:19:20.145909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634c0e911306'
down_revision: Union[str, Sequence[str], None] = 'd749588bb9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('comment', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'comment')
    # ### end Alembic commands ###
