"""rename orders.is_deleted to is_active

Revision ID: a0893bdbf5ca
Revises: dd525f0de51b
Create Date: 2026-05-16 13:01:56.463270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0893bdbf5ca'
down_revision: Union[str, Sequence[str], None] = 'dd525f0de51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
