"""add_is_assembled_to_order_items

Revision ID: ba6ed4745442
Revises: 634c0e911306
Create Date: 2026-05-24 11:01:55.906491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6ed4745442'
down_revision: Union[str, Sequence[str], None] = '634c0e911306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_assembled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'is_assembled')
    # ### end Alembic commands ###
