"""add_warehouse_tables

Revision ID: c58c5ae2848e
Revises: 228c53d28be4
Create Date: 2026-05-15 19:31:42.894159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c58c5ae2848e'
down_revision: Union[str, Sequence[str], None] = '228c53d28be4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packaging_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('packaging_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['packaging_id'], ['packaging_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('batch_year', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'batch_number', 'batch_year', name='uq_product_batch')
    )
    op.create_table('raw_material_stock',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_materials_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('refresh_tokens', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_table('raw_material_stock')
    op.drop_table('products_stock')
    op.drop_table('packaging_stock')
    # ### end Alembic commands ###
