"""add_contact_to_customers

Revision ID: d749588bb9ad
Revises: 2c6f7fffea5d
Create Date: 2026-05-22 07:54:25.888957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd749588bb9ad'
down_revision: Union[str, Sequence[str], None] = '2c6f7fffea5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('contact', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'contact')
    # ### end Alembic commands ###
