"""update orders table: add number, created_at, rename assignee_id to delivery_user_id

Revision ID: dd525f0de51b
Revises: f615fce1d920
Create Date: 2026-05-16 12:38:46.552746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd525f0de51b'
down_revision: Union[str, Sequence[str], None] = 'f615fce1d920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
